name: actions_python_radon
description: Github action for running code complexity analysis 
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  pip_install_command: 
    description: "command used to install python dependancies"
    required: false
    type: string
    default: "pip install radon"
  python_version:
    description: "version of python to run action with"
    required: false
    type: string
    default: "3.x"
  src:
    description: "execution path"
    required: false
    type: string
    default: "."
  grade:
    description: "minimal grade required for pass"
    required: false
    type: string
    default: "B"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: "Setup Python ${{ inputs.python_version }}"
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: "Show Python Version"
      run: python --version
      shell: bash

    - name: "Install Python Dependencies"
      run: |
        python -m pip install --upgrade pip
        ${{ inputs.pip_install_command }}
      shell: bash
       
    - name: "Run Radon"
      run: |
        rc=1
        OUTPUT=$(radon cc -a $1 | tee /dev/tty | tail -1)
        GRADE=$(echo $OUTPUT | grep -oP " \w " | tr -d '[:space:]')
        if [[ $GRADE == $2 || $GRADE < $2 ]] ; then  rc=0 ; fi
        echo $rc >> $GITHUB_OUTPUT
      shell: bash
