name: actions_python_radon
description: Github action for running code complexity analysis with radon
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  grade:
    description: "Minimal grade required to pass"
    required: false
    type: string
    default: "B"
  min:
    description: "Set the minimum MI to display. Expects a letter between A-F. Defaults to A."
    required: false
    type: string
    default: "A"
  src:
    description: "Source file or directory"
    required: false
    type: string
    default: "src"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src }}
    - ${{ inputs.grade }}
